#!/bin/sh
L=$(echo $LANG|sed 's/\..*//')
SALIX_VERSION=13.37
URL_SCHEMA=http://people.salixos.org/tsuren/doc/SalixStartUpGuide_${SALIX_VERSION}_draft3.pdf
URL=$(eval echo $URL_SCHEMA)
wget -N -q "$URL" -O /tmp/SalixStartupGuide-$L.pdf
if [ $? -ne 0 ]; then
  L=$(echo $L|sed 's/_.*//')
  URL=$(eval echo $URL_SCHEMA)
  wget -N -q "$URL" -O /tmp/SalixStartupGuide-$L.pdf
  if [ $? -ne 0 ]; then
    L=en
    URL=$(eval echo $URL_SCHEMA)
    wget -N -q "$URL" -O /tmp/SalixStartupGuide-$L.pdf
  fi
fi
xdg-open /tmp/SalixStartupGuide-$L.pdf
